spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jooq:
    sql-dialect: mysql